name       : iniparser
version    : '4.1'
release    : 1
source     :
    - git|https://github.com/ndevilla/iniparser: deb85ad4936d4ca32cc2260ce43323d47936410d
homepage   : https://github.com/ndevilla/iniparser
license    : MIT
component  : programming.library
summary    : ini file parser
description: |
    This modules offers parsing of ini files from the C level. See a complete documentation in HTML format, from this directory open the file html/index.html with any HTML-capable browser.
build      : |
    %make
install    : |
    install -Dm00644 src/iniparser.h   $installdir/usr/include/iniparser.h
    install -Dm00644 src/dictionary.h  $installdir/usr/include/dictionary.h
    install -Dm00644 libiniparser.so.1 $installdir/usr/lib/libiniparser.so.1
    install -Dm00644 iniparser.pc      $installdir/usr/lib/pkgconfig/iniparser.pc
    ln -sf libiniparser.so.1           $installdir/usr/lib/libiniparser.so
